name: at_app
repository: https://github.com/atsign-foundation/at_app

packages:
  - at_app/*
  - at_app_flutter/*
  - at_app_templates/*
  - at_template/*

scripts:
  build_at:
    run: 'sh tools/full_build_at_template.sh'
  build_aat:
    run: 'sh tools/full_build_at_app_templates.sh'
