name: at_app
repository: https://github.com/atsign-foundation/at_app

packages:
  - packages/*/* # Published packages

scripts:
  postbootstrap: cd templates && dart pub get

  build: sh tools/build_local.sh

