name: at_app
repository: https://github.com/atsign-foundation/at_app

packages:
  - at_app/*
  - at_app_flutter/*
  - at_template/*
  # Non published packages (included for pub get when bootstrapping)
  - templates/*
  - tools/template_bundler/*
scripts:
  build: sh tools/build_all.sh
  build:at_template: sh tools/build_at_template.sh
  build:templates: sh tools/build_templates.sh
  build:generated: sh tools/build_generated.sh

  format: melos exec -- dart format -l 120 .

  analyze: 'melos exec -- dart analyze .'
