name: at_app
repository: https://github.com/atsign-foundation/at_app

packages:
  - packages/*/* # Published packages
  - templates/* # The at_app templates

scripts:
  build: sh tools/build_all.sh
  build:at_app: sh tools/build_at_app.sh
  build:bundler: sh tools/build_bundler.sh
  build:create: sh tools/build_create.sh
  build:templates: sh tools/build_templates.sh
  build:generated: sh tools/build_generated.sh

  setup: sh tools/setup_all.sh
  setup:mason: sh tools/setup_mason.sh

  format: melos exec -- dart format -l 120 .
  analyze: melos exec -- dart analyze .
