name: at_app
description: A command line tool to help developers build an @ platform application.
version: 0.1.0
homepage: https://atsign.dev/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tools:
    sdk: flutter
  at_client_mobile: ^2.0.3
  at_onboarding_flutter: ^2.1.2
  dotenv: ^3.0.0

dev_dependencies:
  pedantic: ^1.10.0
