name: setup_job
description: Setup job for at_app testing

runs:
  using: composite
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
      shell: bash

    - name: Install melos
      run: dart pub global activate melos
      shell: bash

    - name: Bootstrap project with melos
      run: dart pub global run melos bootstrap
      shell: bash

    - name: Install mason_cli
      run: dart pub global run melos run setup:mason
      shell: bash

    - name: Bundle at_app_bundler
      run: dart pub global run melos run bundle:bundler -- --no-analyze
      shell: bash

    - name: Bundle at_app_create
      run: dart pub global run melos run bundle:create -- --no-analyze
      shell: bash

    - name: Bundle templates into at_app
      run: dart pub global run melos run bundle:templates -- --no-analyze
      shell: bash

    - name: Build at_app
      run: dart pub global run melos run build:at_app
      shell: bash
