name: at_backupkey_flutter_template
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_onboarding_flutter: ^4.0.0

  # When depending on this package from a real application you should use:
  #   at_backupkey_flutter: ^x.y.z

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

dependency_overrides:
  at_backupkey_flutter:
#    path: ../
  file_selector_windows: ^0.8.2
  permission_handler: ^9.2.0
  file_selector_macos: ^0.8.2







flutter:
  uses-material-design: true

env:
  override: true
  include: true
  gitignore: true

env_override:
  NAMESPACE: productive2227
  API_KEY: 477b-876u-bcez-c42z-6a3d

android:
  enableR8: true
  kotlinVersion: 1.5.32
  minSdkVersion: '23'

