name: template_bundler
description: A command-line generator for at_app_templates.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  args: ^2.3.0
  mason: ^0.1.0-dev.4
  mason_cli: ^0.1.0-dev.6
  mason_logger: ^0.1.0-dev.4
  pub_semver: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
