name: at_app_templates
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/atsign-foundation/at_app/tree/trunk/at_app_templates/
homepage: https://atsign.dev/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  at_app_flutter: ^4.0.0
  at_client_mobile: ^3.0.3
  at_onboarding_flutter: ^3.0.1
  at_utils: ^3.0.0
  path_provider: ^2.0.5
  timer_builder: ^2.0.0


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
