name: at_chat_flutter_template
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  at_app_flutter: 4.0.0
  at_chat_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

dependency_overrides:
  at_backupkey_flutter:
  #    path: ../
  file_selector_windows: ^0.8.2
  permission_handler: ^9.2.0
  file_selector_macos: ^0.8.2

flutter:
  assets:
    - .env
  uses-material-design: true

env:
  include: true
  gitignore: true
  override: true

env_override:
  NAMESPACE: productive2227
  API_KEY: 477b-876u-bcez-c42z-6a3d

android:
  enableR8: true
  kotlinVersion: 1.5.32
  minSdkVersion: '23'

