name: at_app

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  at_app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup_job

      - name: Dart Analyze
        working-directory: ./packages/at_app
        run: dart analyze

      - name: Unit Tests
        working-directory: ./packages/at_app
        run: dart test

