name: at_app_create

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  analyze_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup_job # Installs the environment and builds the whole repository

      - name: Dart Analyze
        working-directory: ./packages/at_app_create
        run: dart analyze
