name: auto_clean_flutter_cache

on:
  workflow_dispatch:
  schedule:
    - cron: '49 5 * * *' # At 0549 each day

jobs:
  auto_clean_flutter_cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter --version
        shell: bash

      - name: flutter clean
        run: |
            dart pub global activate melos
            dart pub global run melos exec flutter clean

      - uses: ./.github/workflows/install_dependencies_job



