name: CI

on:
  push:
    branches:
      - trunk
  pull_request_target:
    branches:
      - trunk
      - actions-testing

# Test
jobs:
  build:
    permissions:
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest
    outputs:
      build_key: ${{ steps.build_key.outputs.build_key }}
      commit_id: ${{ steps.should_commit.outputs.changes_detected && steps.commit_id.outputs.commit_hash || github.sha }}
    steps:
      - name: Checkout PR
        run: gh pr checkout ${{ github.event.pull_request.number }} --repo atsign-foundation/at_app
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter --version

      - uses: ./.github/workflows/install_dependencies_job
      - uses: ./.github/workflows/build_job

      - id: should_commit
        name: Check for new build
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo 'No changes post-build'
            echo "::set-output name=changes_detected::0"
            exit 0
          else
            echo "::set-output name=changes_detected::1"
          fi

      - id: commit_build
        name: Commit new build
        if: ${{ steps.should_commit.outputs.changes_detected }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m 'Automated build'
          git push
          COMMIT_ID=$(git log --format="%H" -n 1)
          echo "::set-output name=changes_hash::$COMMIT_ID"


  at_app_bundler:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_id }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - run: dart pub global run melos bootstrap

      - name: Dart Analyze
        working-directory: ./packages/at_app_bundler
        # The mason brick in at_app_bundler is not valid dart code
        # Must analyze each directory individually
        run: |
          dart analyze ./lib
          dart analyze ./bin

  at_app_create:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_id }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - run: dart pub global run melos bootstrap

      - name: Dart Analyze
        working-directory: ./packages/at_app_create
        run: dart analyze

  at_app_flutter:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_id }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - run: dart pub global run melos bootstrap

      - name: Dart Analyze
        working-directory: ./packages/at_app_flutter
        run: dart analyze

      - name: Unit Tests
        working-directory: ./packages/at_app_flutter
        run: flutter test

  at_app:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      build_key: ${{ needs.build.outputs.build_key }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_id }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - run: dart pub global run melos bootstrap

      - name: Dart Analyze
        working-directory: ./packages/at_app
        run: dart analyze

      - name: Unit Tests
        working-directory: ./packages/at_app
        run: dart test

  # GENERATED APP TESTS

  # App Templates
  generate-app_template:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_id }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - run: dart pub global run melos bootstrap

      - uses: ./.github/workflows/generated_app_job
        with:
          type: template
          name: app

  # Sample Apps
  generate-at_onboarding_flutter_sample:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_id }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - run: dart pub global run melos bootstrap

      - uses: ./.github/workflows/generated_app_job
        with:
          type: sample
          name: at_onboarding_flutter

  generate-at_contacts_flutter_sample:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_id }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - run: dart pub global run melos bootstrap

      - uses: ./.github/workflows/generated_app_job
        with:
          type: sample
          name: at_contacts_flutter

  # Demo Apps
  generate-snackbar_demo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_id }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - run: dart pub global run melos bootstrap

      - uses: ./.github/workflows/generated_app_job
        with:
          type: demo
          name: snackbar

  generate-snackbar_sender_demo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_id }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - run: dart pub global run melos bootstrap

      - uses: ./.github/workflows/generated_app_job
        with:
          type: demo
          name: snackbar_sender

  generate-chit_chat_demo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_id }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - run: dart pub global run melos bootstrap

      - uses: ./.github/workflows/generated_app_job
        with:
          type: demo
          name: chit_chat

