name: functional_test

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Install melos
        run: dart pub global activate melos

      - name: Install mason_cli
        run: dart pub global activate mason_cli 0.1.0-dev.12

      - name: Bootstrap project with melos
        run: dart pub global run melos bootstrap

      - name: Analyze at_app_flutter
        working-directory: ./packages/at_app_flutter
        run: dart analyze

      - name: Build, format, and analyze at_app_create
        run: dart pub global run melos run build:at_app_create;

      - name: Bundle templates into, format, and analyze at_app
        run: dart pub global run melos run build:templates;

      - name: Build generated apps
        run: dart pub global run melos run build:generated;

      - name: Analyze generated apps
        working-directory: ./build
        run: dart analyze


